[package]
name = "rslox"
description = "A Rust implementation of the Lox Virtual Machine"
version = "0.1.0"
authors = ["Nghi Nguyen <hamnghi250699@gmail.com>"]
edition = "2024"

[dependencies]
clap = { version = "4.6.7", features = ["derive"] }
color-eyre = "0.6.5"
thiserror = "2.0.20"

[dev-dependencies]
rstest = "0.27.0"

[lints.rust]
unsafe_code = { priority = 5, level = "forbid" }
# unused = { priority = -1, level = "allow" }

[profile.dev.package.backtrace]
opt-level = 3
